### ISSUE TITLE
iOS 14 leak conflicts with modal presentation at application launch

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgmediaplayer-apple#100]
If an application using SRG Media Player and presents a modal at startup, this might interfere with the trick used to fix iOS 14 leak (see #93).

**Comment by defagos** [comment]
A fix attempt has been made on `feature/pip-fix-improvement`. It seems to work but requires more careful testing and investigation.

**Comment by pyby** [comment]
It sounds a good proposition.
The `dispatch_after` still required to apply the workaround.

Tested in iOS 14.2 and 14.3, iPadOS 14.2 and 14.3.
The leak issue is always reproductible with iOS 14.2 and 14.3 on a device (iPhone XS in my case).

@oiledCode should give us his feedback too.
