### ISSUE TITLE
Broken Catalyst support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgmediaplayer-apple#105]
Starting with Xcode 12.2 the project does not compile anymore for Catalyst. We get _building for Mac Catalyst-arm64 but attempting to link with file built for unknown-x86_64_ messages during compilation, linker errors for symbols not found (because some files could not be compiled).

Issue is the same with Xcode 13 beta. We are not the only ones affected, e.g.

- https://stackoverflow.com/questions/64865065/mac-catalyst-build-fails-with-building-for-mac-catalyst-x86-64-but-attempting-t
- https://apple.stackexchange.com/questions/408205/can-t-link-c-code-to-dylib-in-xcode-12-2-release-build-only
- https://github.com/realm/realm-cocoa/issues/6619

**Comment by defagos** [comment]
Idea (maybe wrong, but to be investigated): Could it be fixed by setting the minimum deployment target of media player and of its dependencies to iOS 11? We had some strange compilation issues when some libraries had iOS 9 as minimum deployment target.

**Comment by defagos** [comment]
Probably related as well: https://developer.apple.com/forums/thread/658071

**Comment by pyby** [comment]
Fixed in Xcode 14. Same as [SRGAppearance issue](https://github.com/SRGSSR/srgappearance-apple/issues/7).
