### ISSUE TITLE
Speed controls

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgmediaplayer-apple#109]
We should add speed controls:

- [x] Dedicated controller API (probably like `muted`, just stores the value and applies it to the underlying `AVPlayer`).
- [x] Integration in the iOS control center with the dedicated API. (_Not in the iOS control center AFAIK, even over AirPlay and even though the API exists_).
- [x] [Integration](https://developer.apple.com/documentation/avkit/customizing_the_tvos_playback_experience) in the tvOS 15 info panel with a dedicated button. (_Not in Media Player; the player view controller API can be freely used for this specific purpose_).
- [x] On iOS, the easiest is probably to integrate speed selection in the tracks popover (maybe with a settings icon). Other possibilities include a dedicated button or maybe an action which could be optionally added to a custom menu (see #107)
- [x] Allow the user to pick a speed for any kind of stream. For livestreams it will be applied if possible (e.g. when playing in the past for a DVR stream). In live conditions the effective speed will be 1, though `AVPlayer` does not provide this piece of information AFAIK. We should display a message telling the user that the desired speed might not be applied if the stream does not support it.
- [x] Ensure pause / resume from PiP does not reset the rate to 1.
- [x] Check with AirPlay.
- [x] Do not provide any alternative speed list API. We will hardcode standard speeds instead so that we can keep our implementation simpler (layout code would require special care to accommodate for long lists, empty lists as well as truncation of decimals).
- [x] Should probably not provide audio / subtitle selection for audio content.
- [x] Fix issue with playback speeds > 1 making DVR stream playback end abruptly when played at the end of the window. Either this is code we have in our controller which pauses playback, or this is an `AVPlayer` limitation (easy to check with `AVPlayerViewController`). If this is a limitation then we should probably ensure the rate is 1 in live conditions. If not possible then we must probably limit the rate to 1 for livestreams.
- [x] Icon and view title. _Settings_ would probably be better IMHO (as in a lot of cases only speed controls will be available).
- [x] Icons for each settings section? (same icons as for tvOS). Customisable?
- [x] Adjust colors / popover view appearance (e.g. same background for all sections).
- [x] UTs, for example:
  - [x] Start playback with a given speed.
  - [x] Change speed works while paused.
  - [x] Preserve speed while playing another media with the same controller.
  - [x] Preserve speed after a seek.
  - [x] Playback speed near live edge / away from it.
  - [x] Effective playback rate when opening livestream / DVR stream with desired rate 2 (for DVR: Near the edge or away from it).
  - [x] KVO support.
- [x] Accessibility.
- [x] Implement speed controls as standard `SRGMediaPlayerViewController` button

Analytics implemented on top of Media Player (e.g. our SRG Analytics library) can use a combination of the `isLive` flag and the playback rate value to send the correct value, depending on specifications. comScore API, for example, does not provide any way to inform the SDK that a stream is live, so client code has to do this work on its own so that correct values are transmitted.

**Comment by defagos** [comment]
Beware:

- Speeds must be > 0.
- Even with an API providing standard speeds it is possible to set the player rate to any value. Any UI displaying standard speeds should therefore display an _other_ entry if this happens to be the case, with the value (as we do for subtitles not available for some content but still saved at the system level).
- The player rate must be saved separately so that it can be restored after a pause, and used to display the correct choice made by the user.
- Playback rate changes must be notified so that the settings overlay can update itself appropriately.

**Comment by defagos** [comment]
For livestreams locking the playback rate is difficult (as we don't know that a stream is live until we play it). Moreover this seems to work, at least probably using some buffering (< 1 are applied, > 1 are ignored because we cannot play in the future). For the moment I won't do anything special, we'll see if work is really required to prevent playback speed changes for livestreams.

**Comment by defagos** [comment]
I made a proposal with the settings icon replacing the tracks icon but we'll keep the tracks icon.

**Comment by defagos** [comment]
I tested the addition of a playback speed button on tvOS. On my tvOS 15.4 beta device the button is deselected after making a choice. This is apparently not related to changes triggering a button reload but most likely an issue which I don't experience in the ivOS 15.3 simulator.

**Comment by defagos** [comment]
Still asking myself about the icon and popup title. If there are only speed settings available (e.g. stream without subtitles, audio stream) then the icon and title seem a bit odd.

**Comment by defagos** [comment]
I finished the implementation, which is available for review on `feature/speed-playback-speed`.

The [question above](https://github.com/SRGSSR/srgmediaplayer-apple/issues/109#issuecomment-1039186790) still remains to be answered, but the API and testing work is done. I see three possibilities:

- I am the only one to see a problem here, so the work is done.
- A better icon and title are required, but the changes are small.
- We cannot find a simple solution (a different button is not an option at the moment), in which case we should keep the good UI changes (refactoring of the tracks popover) but discard the playback speed section, just keeping the controller API for the moment.

**Comment by defagos** [comment]
The speed has been restricted to 1x for livestreams without DVR. Slower speeds could work (buffering would still need to be studied) but the UX obtained is awkward (you cannot fast forward to the live conditions).

**Comment by pyby** [comment]
@defagos Thanks for driving this nice player feature to the SRG SSR Apple player.
