### ISSUE TITLE
Leak on AVFAudio -[AVAudioSessionPortDescription initWithPortType:]

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srgmediaplayer-apple#21]
### Issue overview

When calling -[AVAudioSession currentRoute], little leaks appear. (16 to 192 bytes).

> Check the correct option below

* [X] Incorrect behavior
* [ ] Feature request
* [ ] Crash
* [ ] Help / documentation
* [ ] Other: _classification_

### Description of the problem

Using Instruments and the demo applications. Use the "Leak checks" tool, we can find those little leak.
From AudioToolbox or AVFAudio libraries.

### Environment information

* Library version: 2.0

### Reproducibility

* [X] Always reproducible
* [ ] Difficult to reproduce

### Links

http://stackoverflow.com/questions/41529859/instruments-show-leak-in-avaudiosessionportdescription-initwithporttype-xcod

**Comment by defagos** [comment]
This is probably an Apple bug. We should file a report.

**Comment by defagos** [comment]
The leaks have been fixed. I could not reproduce them with an iOS 11 device (though I found other `FigXPCMessageCopyCFObject` leaks).

With iOS 12, no leaks can be found anymore.
