### ISSUE TITLE
360° playback possible improvements

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgmediaplayer-apple#39]
We now support 360 video playback directly in SRG Media Player. There are still a few ideas which could be implemented:

* Limit motions to +pi/2 and -pi/2 when moving up and down.
* Disable pan gesture with cardboard and re-center.
* Add inertia to pan gestures.
* Implement camera reset to face the content.
* Have camera orientation stable under device rotation.

None of those have been discussed or are mandatory, I just wanted to keep track of what could be possible if we want to go further.

**Comment by vpdn** [comment]
Cool, is 360 Videos already part of the current LB release? Would love to update to test out. Also would like to see whether this might interfere with our "pull down to dismiss" gesture recognizer.

**Comment by defagos** [comment]
Moreover, there are a few issues on iOS 9, due to issues with `SKVideoNode`:

* 360° playback automatically starts, even if the media was only prepared. See for example the following [post](https://stackoverflow.com/questions/31985073/why-does-skvideonode-automatically-starts-playing-video-on-ios9).
* `SKVideoNode` leaks. See for example the following [github issue](https://github.com/NYTimes/ios-360-videos/issues/46).

These problems have been fixed with iOS 10. I mitigated the second issue since it can be quite annoying (playback is paused, but the leaks is not removed).I recommend we do not lose time fixing these issues further, though.

**Comment by defagos** [comment]
@vpdn This is part of the next LB release.

**Comment by defagos** [comment]
Note that currently:

* Playback is paused when switching between normal and cardboard 360° playback. This is due to `SKVideoNode` being deallocated. Currently we let things as is, since this could make sense after all. If we get complaints we'll try to improve such transitions.
* Until iOS 11, Split Over on an iPad stops the video frame (but not the playback itself) for 360° playback. This is not the case anymore with iOS 11: As for normal videos, playback continues. For the moment we won't write code to deal with this minor inconsistency, which will after all disappear when iOS 11 is the minimum version we support.

**Comment by defagos** [comment]
360° has been in use in our apps for quite some time and the improvements I suggested do not seem necessary at the moment.
