### ISSUE TITLE
Playback does not end with truncated Akamai streams when subtitles are displayed

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgmediaplayer-apple#65]
When playing a truncated Akamai stream with subtitles enabled (truncation via `start` and `end` parameters), the subtitles track is correctly aligned at the beginning, but its length is bigger than the stream duration. As a result, the player never reaches the end state.

### Issue type

Incorrect behavior

### Description of the problem

Subtitles track for truncated streams is an Akamai beta feature. We should report the bug and implement a workaround in the meantime.

### Environment information

* Library version: Any
* iOS version: Any
* Device: Any

### Reproducibility

Always reproducible

### Steps to reproduce

1. Play an Akamai stream having subtitles, truncated with `start` and `end` parameters, for example https://rtsvodww-vh.akamaihd.net/i/journ-19h30/2019/journ-19h30_20190603_full_ca7d9d68-58aa-4acd-b2e5-a6af7470bc8d-,301k,701k,1201k,2001k,3501k,6001k,.mp4.csmil/master.m3u8?caption=journ-19h30/2019/journ-19h30_20190603_full_500048834.m3u8:fra:Fran%C3%A7ais&start=267.36&end=387.36
1. Enable subtitles.
1. Wait until playback reaches the end. The player never ends playback.

**Comment by pyby** [comment]
`feature/akamai-subtitles-end-fix` is our proposition and it's merged to `develop`.
