### ISSUE TITLE
Player sometimes stays stuck in the stalled state

### ISSUE THREAD

**Issue by defagos** [SRGSSR/srgmediaplayer-apple#88]
When playing videos mostly, sometimes the player stays in the stalled state at start. The media plays, but the state is stalled (with the advanced player demo, you can see that the loading indicator spins indefinitely).

When this happens, inducing a player state transition (e.g. pause / play or seek) fixes the issue, but this is of course not a solution.

**Comment by defagos** [comment]
I have a fix proposal on `feature/stall-detection-fix`. I think that `playbackIsLikelyToKeepUp` is not always correctly triggered, and I propose a more self-contained implementation which relies only on playback states.

I propose we check the logic together and test this issue for a while (as this is difficult to simulate or write as a UT).

**Comment by pyby** [comment]
To test in Play SRG nightlies. your branch is now on `develop` and in [SRGSSR/playsrg-ios](https://github.com/SRGSSR/playsrg-ios/commit/6160a6cbfc2663df0febbd4b4361a1b738337b2b).
